name: commardArgsReal
version: '${project.version}'
main: me.pingu.commardargsreal.CommardArgsReal
api-version: '1.20'
commands:
  repeat:
    description: repeat msg back to you
    usage: /<command>
    


