name: fart
version: '${project.version}'
main: me.pingu.fart.Fart
api-version: '1.20'
commands:
  fart:
    description: fart and kill
    usage: /<command> <player>

  enablefart:
    description: enable fart command
    usage: /<command>
    permission: op

  diablefart:
    description: disable fart command
    usage: /<command>
    permission: op





